"""Built-in profile fallbacks (spec section 69).

The same profiles ship as YAML inside ``default-pack/profiles/``; these
hardcoded copies are used only when a custom pack omits a standard profile so
configuration referencing a builtin id never breaks.
"""

from __future__ import annotations

from chaff_generator.core.models import LayoutMode
from chaff_generator.profiles.models import Profile

BUILTIN_PROFILES: dict[str, Profile] = {
    "realistic-desktop": Profile(
        id="realistic-desktop",
        name="Realistic Desktop",
        description="Many small-to-medium realistic everyday files.",
        directory_layout=LayoutMode.REALISTIC,
        format_weights={
            "txt": 14,
            "md": 8,
            "eml": 16,
            "docx": 14,
            "pdf": 12,
            "csv": 8,
            "xlsx": 10,
            "pptx": 6,
            "json": 4,
            "html": 4,
            "vcf": 2,
            "ics": 2,
        },
        content_domains={
            "business": 30,
            "personal": 25,
            "projects": 20,
            "finance": 15,
            "technical": 10,
        },
        size_profile={},
        avg_file_size_bytes=120 * 1024,
    ),
    "office-workstation": Profile(
        id="office-workstation",
        name="Office Workstation",
        description="Business documents, spreadsheets, email, and presentations.",
        directory_layout=LayoutMode.REALISTIC,
        format_weights={
            "eml": 20,
            "docx": 18,
            "pdf": 15,
            "xlsx": 12,
            "txt": 10,
            "csv": 8,
            "pptx": 7,
            "md": 5,
            "json": 3,
            "html": 2,
        },
        content_domains={
            "business": 40,
            "projects": 25,
            "finance": 15,
            "meetings": 10,
            "technical": 10,
        },
        size_profile={},
        avg_file_size_bytes=150 * 1024,
    ),
    "personal-computer": Profile(
        id="personal-computer",
        name="Personal Computer",
        description="Personal documents, correspondence, bills, and records.",
        directory_layout=LayoutMode.REALISTIC,
        format_weights={
            "txt": 18,
            "md": 12,
            "eml": 16,
            "pdf": 16,
            "docx": 12,
            "csv": 6,
            "xlsx": 8,
            "json": 4,
            "html": 8,
        },
        content_domains={
            "personal": 45,
            "finance": 20,
            "business": 15,
            "projects": 10,
            "technical": 10,
        },
        size_profile={},
        avg_file_size_bytes=100 * 1024,
    ),
    "developer-workstation": Profile(
        id="developer-workstation",
        name="Developer Workstation",
        description="Projects, notes, exports, logs, and plausible code/config files.",
        directory_layout=LayoutMode.REALISTIC,
        format_weights={
            "txt": 12,
            "md": 16,
            "log": 12,
            "json": 10,
            "xml": 5,
            "csv": 6,
            "html": 5,
            "dev": 22,
            "pdf": 6,
            "docx": 6,
        },
        content_domains={"technical": 45, "projects": 30, "business": 15, "personal": 10},
        size_profile={},
        avg_file_size_bytes=80 * 1024,
    ),
    "balanced": Profile(
        id="balanced",
        name="Balanced",
        description="Realistic everyday files plus larger CSV, logs, PDFs, and attachments.",
        directory_layout=LayoutMode.REALISTIC,
        format_weights={
            "txt": 10,
            "log": 8,
            "md": 6,
            "eml": 14,
            "docx": 12,
            "pdf": 14,
            "csv": 12,
            "xlsx": 10,
            "pptx": 5,
            "json": 5,
            "html": 4,
        },
        content_domains={
            "business": 30,
            "projects": 25,
            "technical": 20,
            "finance": 15,
            "personal": 10,
        },
        size_profile={},
        avg_file_size_bytes=250 * 1024,
    ),
    "storage-test": Profile(
        id="storage-test",
        name="Storage Test",
        description="Normal files plus large deterministic storage payloads.",
        directory_layout=LayoutMode.SIMPLE,
        format_weights={
            "txt": 5,
            "md": 3,
            "eml": 6,
            "docx": 6,
            "pdf": 6,
            "csv": 6,
            "xlsx": 5,
            "pptx": 2,
            "dat": 55,
            "log": 6,
        },
        content_domains={"business": 30, "projects": 25, "technical": 25, "finance": 20},
        size_profile={},
        avg_file_size_bytes=40 * 1024 * 1024,
        payload_default=True,
    ),
    "mixed": Profile(
        id="mixed",
        name="Mixed Workstation",
        description="A blend of personal, business, communication, and technical files.",
        directory_layout=LayoutMode.REALISTIC,
        format_weights={
            "txt": 12,
            "md": 8,
            "eml": 15,
            "docx": 13,
            "pdf": 13,
            "csv": 9,
            "xlsx": 10,
            "pptx": 5,
            "json": 5,
            "html": 4,
            "vcf": 2,
            "ics": 2,
            "log": 2,
        },
        content_domains={
            "business": 30,
            "personal": 20,
            "projects": 20,
            "finance": 15,
            "technical": 15,
        },
        size_profile={},
        avg_file_size_bytes=150 * 1024,
    ),
}
